EGC-G2-tortilla/tortilla-hub

app/modules/auth/routes.py, app/modules/community/templates/community/create_community.html
Se ha cambiado zenodo.scripts por fakenodo.scripts en create_community.html.
El cambio de zenodo a fakenodo ha causado este error. Como es natural, se debe de solucionar.
Solo afecta al archivo html.
No se han cambiado las pruebas.
=> fix: solucionado error en vista de create_community

.github/workflows/lint.yml
Se ha comprobado el funcionamiento del workflow tras las modificaciones en el repositorio de uvlhub-practicas, se espera que se comporte de igual manera en tortilla-hub.
Closes #50
=> Workflow se lanza adecuadamente para pushes en main/ develop 

app/modules/dataset/seeders.py
Se han modificado aquellos datasets que tenian información repetida, con el fin de mejorar la calidad de los datos de prueba
=> Seeders de dataset ahora no contienen datos repetidos closes #47

.github/workflows/deployment_on_dockerhub.yml
Se ha corregido la ruta a la imagen Dockerfile.dev en el workflow de construcción
=> Fix: Ruta imagen Dockerfile.dev en .yml

app/modules/community/templates/community/community.html, app/modules/community/templates/community/community_info.html, app/modules/community/templates/community/community_members.html, app/modules/community/tests/test_selenium.py, app/modules/dataset/assets/scripts.js, app/modules/dataset/routes.py, app/modules/dataset/services.py, app/templates/base_template.html
Se ha implementado la funcionalidad de las comunidades para poder subir datasets a una comunidad. Además, se ha solucionado la incidencia #86 que no se podía ver el link para acceder a las comunidades si no estabas logueado.
Se entiende que en entre las comunidades de las comunidades debe de estar incluida la de subir datasets a una comunidad.
Se ha creado una ruta en específico para poder subir los datasets a una comunidad y se ha creado una vista para esta url. 
Se ha hecho un test de selenium que prueba toda la funcionalidad implementada.
=> Implementación de funcionalidad de comunidades para subir datasets

app/modules/dataset/templates/dataset/view_dataset.html
Se ha aplicado un pequeño cambio en la estética de los botones de la vista de los datasets
=> Fix: Botones de subida de archivos en la vista de detalles de un dataset

.github/workflows/lint.yml
Se detalla la información en #50
=> Incidencia: Workflow de lint y formatting es lanzado correctamente en PRs

app/modules/dataset/tests/test_unit_staging_area.py
Realizar pruebas unitarias del WI relativo a la staging area 
Verificar la funcionalidad de dicho WI y facilitar procesos de CI 
Se ven únicamente afectados ficheros pertenecientes al modulo dataset.
No aplica
No aplica
=> Añadidos los tests unitarios closes #104

app/modules/dataset/tests/locustfile.py
**Descripción del cambio**: Se han implementado pruebas de rendimiento y carga con Locust para evaluar la capacidad del sistema en la visualización y descarga de datasets.
**Motivación**: Asegurar que las funcionalidades clave (visualización, descarga y autenticación) puedan manejar múltiples usuarios concurrentes, manteniendo un rendimiento estable bajo diferentes niveles de carga.
**Impacto**: Estas pruebas mejoran la confiabilidad del sistema al identificar posibles cuellos de botella y garantizan que el sistema sea escalable y estable frente a altos volúmenes de usuarios.
**Pruebas realizadas**:
- **Visualización de datasets**: Simula múltiples usuarios accediendo a un dataset específico.
- **Descarga de datasets**: Evalúa la capacidad de manejar solicitudes concurrentes de descarga. …
=> Feat: tests rendimiento con locust para improve ui

app/modules/dataset/templates/dataset/view_dataset.html, app/modules/dataset/tests/test_selenium.py
**Descripción del cambio**: Se han implementado pruebas de interfaz con selenium para la funcionalidad de _Improve UI_.
**Motivación**: Garantizar que la nueva estética implementada para que la vista se asemeje a la propuesta por GitHub renderiza correctamente los distintos elementos y que aquellos que realizan acciones en la vista funcionan según lo esperado.
**Impacto**: Las pruebas añadidas mejoran la cobertura de pruebas del sistema, asegurando que los cambios en la interfaz de usuario no afecten negativamente la funcionalidad existente. Esto aumenta la confiabilidad y estabilidad de la aplicación, facilitando el mantenimiento y la detección temprana de posibles regresiones en futuras modificaciones de la UI.
**Pruebas realizadas**:
- **test_buttons_upload_and_download()**: Verifica …
=> Feat: tests de selenium para la vista de detalle de los datasets

app/modules/dataset/routes.py, app/modules/dataset/services.py, app/modules/dataset/templates/dataset/list_datasets.html
Se ha implementado la opción de poder unstagear todos los datasets que se encuentren en la zona de preparación
Cambios motivados por la mejora del WI 
Se ven únicamente afectados ficheros pertenecientes al modulo dataset.
Evidencia de pruebas
No aplica
Instrucciones adicionales
No aplica
=> WI: Añadido poder unstagear todos los datasets simultáneamente

app/modules/community/routes.py, app/modules/community/templates/community/my_communities.html, app/modules/community/tests/test_selenium.py, app/modules/dataset/routes.py, app/modules/dataset/tests/test_unit_staging_area.py, app/templates/base_template.html
Se ha creado una nueva vista para que cada usuario pueda ver las comunidades a las que pertenece.
Se pretende que ayude al usuario a poder acceder a sus comunidades más facilmente. De no existir esta ruta, el usuario tendría que revisar todas las comunidades hasta encontrar la suya.
Se ha creado una nueva ruta para conseguir esta funcionalidad.
Se ha creado un test de selenium para poder probar esta funcionalidad.
=> Creada una ruta específica para poder ver las comunidades a las que pertenezco

app/modules/auth/tests/test_unit.py
Se han añadido los tests relativos al WI: Sync with Github/Gitlab
Closes #163, #164 
Es necesario testear la funcionalidad para comprobar su correcto funcionamiento y posible corrección de errores
Bajo
Todos los tests añadidos se ejecutan correctamente de manera individual y a través de Rosemary CLI
N/A
=> Task/test sync with GitHub/Gitlab

docker/entrypoints/development_render_entrypoint.sh, docker/images/Dockerfile.render-dev, scripts/development_render_entrypoint.sh
Co-authored-by: Daniel Fernández <danfercab@alum.us.es>
Closes #167
=> feat: Añadir entrypoint e imagen nueva para datos de prueba en develop.

app/modules/community/routes.py, app/modules/community/templates/community/community_members.html, app/modules/community/tests/test_selenium.py, app/modules/community/tests/test_unit.py
Se han revisado y añadido test unitarios de comunidades para aumentar el coverage.
Es importante que las funcionalidades tengan tests para así poder comprobar en todo momento que la aplicación funciona como debería. Además, debe de tener un  buen coverage para así poder asegurar de que todo se está testeando.
Se han modificado y creado tests de comunidades.
Esta pull request es específica de revisión de tests, por lo que solo contiene pruebas.
=> Se han añadido tests unitarios a community para aumentar coverage

vagrant/04_install_dependencies.yml
El objetivo de esta PR es solucionar un error detectado en la instalación de dependencias de Vagrant.
Se realizará el merge directamente ya que estos cambios han sido comprobados y validados previamente en el repositorio oficial de la asignatura.
=> Solución de error detectado en el código original de uvlhub

app/modules/discord_bot/bot.py, app/modules/discord_bot/tests/test_unit.py
Se añaden 6 tests unitarios que cubren los 5 últimos slash_commands.
=> Tests unitarios del bot de discord

app/modules/dataset/forms.py, app/modules/dataset/services.py, app/modules/dataset/templates/dataset/upload_dataset.html
Se hah soluciado el error de la issue #230 de que en el formulario de subir un dataset hay un valor que no se entiende el valor que se debe de introducir, el de publication DOI.
Mejorar la usabilidad del formulario
Se ha modificado la vista del formulario de subir un dataset
Se han ejecutado las pruebas, aunque simplemente se haya cambiado la vista
=> Incidencia: en el formulario de subir un dataset hay un valor que no se entiende el valor que se debe de introducir

app/modules/auth/tests/locustfile.py, app/modules/auth/tests/test_unit.py, requirements.txt
Comprobar que los tests funcionan correctamente, falta por añadir los tests de carga de github.
=> Tests de carga de multiple Login

app/modules/auth/models.py, app/modules/dataset/routes.py, app/modules/dataset/tests/locustfile.py, app/modules/dataset/tests/locustfile_staging_area.py, app/modules/dataset/tests/test_unit_staging_area.py
Separar los tests de carga segun responsabilidad y la mejora de la comprobación de las respuestas a las peticiones realizadas
Solucionar el bug de que las respuestas de las peticiones se verifiquen de manera correcta
Módulo de testing de Dataset
No aplica
Para facilitar la prueba se ha verificar que no haya errores en la ejecución del fichero utilizando:
locust -f app/modules/dataset/tests/locustfile_staging_area.py
=> Fix: Tests de carga de la Staging Area

README.md, app/modules/community/tests/test_selenium.py
**Descripción del cambio:**
Se ha actualizado el archivo README.md y test_selenium.py de community del proyecto corrigiendo numerosos errores de formato detectados por Codacy.
**Motivación / Impacto:**
Este cambio mejora la calidad y la estructura del código del proyecto.
**Instrucciones:**
Aceptar esta Pull Request comprobando antes que codacy no detecta ningún error de antmacfer1@alum.us.es o de delsanrub@alum.us.es.
=> Fix: cambios para corregir errores de codacy

app/modules/discord_bot/bot.py, app/templates/base_template.html
Se añade el botón en la sidebar y se cambia la descripción e hipervínculos de algunos comandos.
Closes #252
=> Añadir boton de invitación del bot y arreglar hipervinculos.

app/modules/public/templates/public/index.html, app/static/css/own.css
Se ha actualizado la tarjeta de bienvenida que aparece en la página de inicio para que muestre una felicitación de navidad con un color divertido.
Este cambio proporcionará una estética fresca y alegre a la página, dado así también sensación de actualidad acorde a las fiestas que vivimos a fecha de la finalización del proyecto.
Se debe comprobar visualmente que el cambio se ha realizado correctamente.
=> feat:modificacion de la tarjeta de bienvenida
